#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend airbnb-site
    bind *:80
    mode http
    default_backend my-app

backend my-app
    balance roundrobin
    server 101117-web-01 100.26.231.29:80 check
    server 101117-web-02 18.214.87.0:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
