-- setting up and starting replication
STOP SLAVE;

CHANGE MASTER TO
MASTER_HOST='100.26.231.29',
MASTER_USER='replica_user',
MASTER_PASSWORD='replica_user',
MASTER_LOG_FILE='mysql-bin.000001',
MASTER_LOG_POS=154;

START SLAVE;
SHOW SLAVE STATUS\G

