#!/usr/bin/env bash
# install the ufw firewall and deny incoming traffic on all ports
# except 22, 80 and 443.

sudo apt install -y ufw
sudo ufw enable
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
